### ISSUE TITLE
when the code will be released?

### ISSUE THREAD

**Issue by LeeDoYup** [tgisaturday/L-Verse#1]
I wonder when the code will be released. Thank you.

**Comment by tgisaturday** [comment]
Hi @LeeDoYup, thank you for your interest on our work! As our paper got accepted to CVPR 2022, we will update our code soon with the camera-ready version of our paper.

**Comment by LeeDoYup** [comment]
@tgisaturday Thanks for the awesome project !

**Comment by GoelBiju** [comment]
Many thanks, @tgisaturday, I was about to email you regarding if the code would be released as well! Awesome work!
